### PR TITLE
Remove duplicate sketch file

### PR DESCRIPTION
**Pull request by per1234**
The same code already exists at examples/RWS_BMP180_test so this file is unnecessary and only causes confusion and increased maintenance.

### CODE REVIEW

**Comment by sellensr** [comment]
The duplication allows the entire library file structure to function within the Arduino sketch folder during development using the IDE, while also finding any examples when it is later installed in the library directory. For me, it decreases maintenance.

**Comment by per1234** [comment]
I do a similar thing with my libraries, but I add that file to my .git/info/exclude file so that it's not published.

**Comment by sellensr** [comment]
I added it to both the .gitignore in the primary directory (seems to be the way it's done in the desktop app) and to the .git/info/exclude as you suggested. Probably redundant... Thanks for teaching me a new trick.

**Comment by per1234** [comment]
I'm glad if I was able to be helpful.

The problem with .git/info/exclude is it's not part of the repository so if someone clones this repository they won't get your custom .git/info/exclude file. .gitignore is part of the repository so it's shared between all users. .gitignore is good for ignoring build artifacts (not a factor for Arduino projects because those files are put in an external temporary folder), where all users will be generating these same files and you don't want someone submitting a PR with a bunch of garbage files included. In the case of a dummy .ino file used to allow the Arduino IDE to edit libraries I prefer .git/info/exclude but really that's just a personal preference. There's certainly no harm in using both files. I often have a notes.txt file in my project folders for my personal messy "to do" list, etc. that I also add to .git/info/exclude because I don't want to publish it.

**Pull request merged**
